fix

diff --git a/src/jobs/build_and_push.yml b/src/jobs/build_and_push.yml
--- a/src/jobs/build_and_push.yml
+++ b/src/jobs/build_and_push.yml
@@ -103,10 +103,14 @@ parameters:
       e.g docker -u $DOCKER_ID -p $DOCKER_PASSWORD
     type: steps
     default:
-      - run: >-
-          echo "Error - container_registry_login parameter is set to true without
-           any registry_login steps."
-      - run: exit 1
+      - run:
+          name: Container Registry Login Error
+          command: >-
+            echo "Error - container_registry_login parameter is set to true without
+             any registry_login steps."
+      - run:
+          name: Exit on Registry Login Error
+          command: exit 1
 
   dockerfile:
     type: string
